@startuml
package "com.techreturners.teama.healthyfood.api" {

    HealthyFoodController --> HealthyFoodService
    HealthyFoodService --> HealthFoodServiceImpl
    HealthFoodServiceImpl--> DietRepository
    HealthFoodServiceImpl--> IngredientsRepository
    HealthFoodServiceImpl--> CategoryRepository
    HealthFoodServiceImpl --> MealRepository

    DietRepository --> Diet
    CategoryRepository --> Category
    MealRepository --> Meal
    MealRepository --> MealIngredientAs
    IngredientsRepository --> Ingredients

    MealPlanController --> MealPlanService
    MealPlanService --> MealPlanServiceImpl
    MealPlanServiceImpl --> MealPlanRepository
    MealPlanRepository --> MealPlan

    UserController --> UserService
    UserService --> UserServiceImpl
    UserServiceImpl --> UserRepository
    UserRepository <-- User


    Class HealthyFoodController{

        @Autowired
        healthyFoodManagerService : HealthyFoodService;
        getAllIngredients() : ResponseEntity
        getAllDiets() : ResponseEntity
        getAllCategories() : ResponseEntity
        getMeals(int calories, String excludedIngredients, String diet, String category) : ResponseEntity
    }

    Class MealPlanController{
        getMealPlan(Long userId) : ResponseEntity
        createMealPlan(mealid:Long, userId:Long, dateadded:LocalDateTime ) :ResponseEntity

    }
    Class UserController{
        @Autowired
        userService : UserService

        getUserById(userId:Long):ResponseEntity
        addUser(user: User) ResponseEntity
        updateUserById( userId : Long, user :User) ResponseEntity
         deleteUserById(userId : Long) ResponseEntity
    }

    Interface HealthyFoodService{
        getAllIngredients() : ResponseEntity
        getAllDiets() : ResponseEntity
        getAllCategories() : ResponseEntity
        getMeals(calories:Integer, excludedIngredients:List<Long>,  diets:List<Long>, category:List<Long>) : ResponseEntity

    }
    Interface MealPlanService{
        getAllMealPlans(userId:Long) : List<MealPlan>
            createMealPlan(mealid:Long, userId:Long, date:LocalDateTime) :MealPlan
    }
    Class HealthFoodServiceImpl {
        @Autowired
        MealRepository mealRepository;
        UserRepository userRepository;
        MealPlanRepository mealPlanRepository;

        public getAllIngredients()
        public getAllDiets()
        public getAllCategories()
        public getMeals(Integer calories, List<Long> excludedIngredients, List<Long> diets, List<Long> category)
    }

    Class MealPlanServiceImpl{
        @Autowired
        mealRepository:MealRepository
        userRepository:UserRepository
        mealPlanRepository:MealPlanRepository

        getAllMealPlans(userId:Long) : List<MealPlan>
        createMealPlan(mealid:Long, userId:Long, date:LocalDateTime) :MealPlan
    }

    Interface UserService {
        getAllUsers() :List<User>
        getUserById(id : Long) : User
        insertIntoUser(user:User) :User
        deleteUserById(id : Long) : void
        updateUserById(id : Long) : void
    }
    Class UserServiceImpl{
    @Autowired
        UserRepository userRepository;

        getAllUsers() : List<User>
        getUserById(id:Long) :User
        insertIntoUser(user: User): User
        deleteUserById(id : Long) : void
        updateUserById(id : Long) : void
    }

    Class User {
        id : Long
        email:String
        firstname : String
        lastname: String
        dietid : String
        exclude : String
        dateadded : LocalDateTime
    }

    Class Ingredients{
        id :Long
        name : String
        calories :int
        carbohydrates: int
        fat : int
        protein : int
        photo :String
    }

    Class MealIngredientAs{
        id : Long
        mealid : int
        ngredeintid : int
        quantity : int
    }

    Class Diet{
        id : Long
        name : String
        photo: String
    }

    Class Meal{
        id : Long
        name : String
        shortdesc : String
        longdesc : String
        category : String
        preptime : int
         serving: int
         diet :String
         photo : String
         url : String
         dateadded : LocalDateTime
    }

    Class Category{
        id :Long
        name : String
    }

    Class MealPlan{
        id : Long
        userid : int
        mealid : int
         date : LocalDateTime
    }
    Interface UserRepository{
    }
    Interface CategoryRepository{
    }
    Interface IngredientsRepository{
    }
    Interface DietRepository{
    }
    Interface MealPlanRepository{
    }
    Interface MealRepository{
    }
    Interface MealIngredientAs{
    }
}
@enduml